# Copyright (c) 2024-2026 Revclip. All rights reserved.
name: Revclip
options:
  deploymentTarget:
    macOS: "14.0"
  bundleIdPrefix: com.revclip
  xcodeVersion: "16.0"
  createIntermediateGroups: true

targets:
  Revclip:
    type: application
    platform: macOS
    dependencies:
      - sdk: ApplicationServices.framework
    sources:
      - path: Revclip
        excludes:
          - "Vendor/Sparkle/**"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.revclip.Revclip
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        ARCHS: "arm64 x86_64"
        ONLY_ACTIVE_ARCH: false
        INFOPLIST_FILE: Revclip/Info.plist
        CODE_SIGN_ENTITLEMENTS: Revclip/Revclip.entitlements
        ENABLE_HARDENED_RUNTIME: true
        CODE_SIGN_IDENTITY: ""
        CLANG_ENABLE_OBJC_ARC: true
        GCC_PREFIX_HEADER: Revclip/Revclip-Prefix.pch
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        FRAMEWORK_SEARCH_PATHS: "$(PROJECT_DIR)/Revclip/Vendor"
        OTHER_LDFLAGS:
          - "$(inherited)"
          - "-lsqlite3"
        CLANG_ENABLE_MODULES: true
        GCC_PRECOMPILE_PREFIX_HEADER: true
      configs:
        Release:
          ONLY_ACTIVE_ARCH: false
          CODE_SIGN_IDENTITY: "Developer ID Application"
        Debug:
          ONLY_ACTIVE_ARCH: true
          CODE_SIGN_IDENTITY: ""

  RevclipTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: RevclipTests
    dependencies:
      - target: Revclip
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Revclip.app/Contents/MacOS/Revclip"
        BUNDLE_LOADER: "$(TEST_HOST)"
