# Copyright (c) 2024-2026 Revclip. All rights reserved.
name: Revclip
options:
  deploymentTarget:
    macOS: "14.0"
  bundleIdPrefix: com.revclip
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  knownRegions:
    - en
    - ja
    - de
    - zh-Hans
    - it

targets:
  Revclip:
    type: application
    platform: macOS
    dependencies:
      - sdk: ApplicationServices.framework
      - sdk: Carbon.framework
      - sdk: ServiceManagement.framework
      - framework: Revclip/Vendor/Sparkle/Sparkle.framework
        embed: true
        weak: true
    info:
      path: Revclip/Info.plist
      properties:
        CFBundleName: "Revclip"
        CFBundleDisplayName: "Revclip"
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleVersion: "15"
        CFBundleShortVersionString: "0.0.15"
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        CFBundlePackageType: "APPL"
        CFBundleSignature: "????"
        NSMainNibFile: "MainMenu"
        LSUIElement: true
        LSMinimumSystemVersion: "$(MACOSX_DEPLOYMENT_TARGET)"
        NSPrincipalClass: "NSApplication"
        NSHumanReadableCopyright: "Copyright © 2024-2026 Revclip. All rights reserved."
        CFBundleIconName: "AppIcon"
        SUFeedURL: "https://github.com/sasuketorii/rev-clip/releases/latest/download/appcast.xml"
        SUPublicEDKey: "jW5CH5/B8IApRFYiwOGot/VUmo0uqvE1LawgUG1igUk="
        NSAccessibilityUsageDescription: "Revclip needs accessibility access to paste clipboard items into other applications."
    sources:
      - path: Revclip
        excludes:
          - "Vendor/Sparkle/**"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.revclip.Revclip
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        ARCHS: "arm64 x86_64"
        ONLY_ACTIVE_ARCH: false
        INFOPLIST_FILE: Revclip/Info.plist
        CODE_SIGN_ENTITLEMENTS: Revclip/Revclip.entitlements
        ENABLE_HARDENED_RUNTIME: true
        CODE_SIGN_IDENTITY: ""
        CLANG_ENABLE_OBJC_ARC: true
        GCC_PREFIX_HEADER: Revclip/Revclip-Prefix.pch
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        FRAMEWORK_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Revclip/Vendor"
          - "$(PROJECT_DIR)/Revclip/Vendor/Sparkle"
        OTHER_LDFLAGS:
          - "$(inherited)"
          - "-lsqlite3"
        CLANG_ENABLE_MODULES: true
        GCC_PRECOMPILE_PREFIX_HEADER: true
      configs:
        Release:
          ONLY_ACTIVE_ARCH: false
          CODE_SIGN_IDENTITY: "Developer ID Application"
        Debug:
          ONLY_ACTIVE_ARCH: true
          CODE_SIGN_IDENTITY: ""

  RevclipTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: RevclipTests
    dependencies:
      - target: Revclip
    settings:
      base:
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Revclip.app/Contents/MacOS/Revclip"
        BUNDLE_LOADER: "$(TEST_HOST)"
